[package]
name = "bevy_window_icon"
version = "0.3.0"
edition = "2021"

license = "MIT OR Apache-2.0"
description = "Window icons in Bevy"
homepage = "https://github.com/0crispy/bevy_window_icon"
repository = "https://github.com/0crispy/bevy_window_icon"
readme = "README.md"
documentation = "https://docs.rs/bevy_window_icon"

[dependencies]
bevy = { version = "0.13", default-features = false, features = [
    "bevy_winit"
]}
winit = "0.29"
image = "0.25"
[dev-dependencies] 
bevy = "0.13"
